[build-system]
requires = [
    "setuptools>=78",
    "wheel",
    "cmake",
    "ninja",
    "build"
]

build-backend = "setuptools.build_meta"

[project]
name = "pyvgx"
dynamic = ["version"]
requires-python = ">= 3.9"
authors = [{ name = "Stian Lysne", email = "slysne.dev@gmail.com" }]
description = "PyVGX - Vector Graph Index Python Extensions"
readme = { file = "README.md", content-type = "text/markdown" }

[project.scripts]
vgxadmin = "pyvgx_scripts.vgxadmin:main"

[tool.setuptools]
script-files = ["pyvgx/src/py/vgxdemoservice", "pyvgx/src/py/vgxdemoservice.cmd", "pyvgx/src/py/vgxdemoservice.py", "pyvgx/src/py/vgxdemoplugin.py"]


[tool.cibuildwheel]
build = "cp312-*"
build-frontend = "build"
skip = ["*-win32", "*-manylinux_i686", "*-musllinux*"]
# The placeholder {project} points to the temporary project directory.
test-command = "bash {project}/pyvgx/bin/test_pip_package.sh"

[tool.cibuildwheel.linux]
archs = "x86_64"