#ifndef VERSIONGEN_H_
#define VERSIONGEN_H_

#define VERSIONGEN_XSTR( s ) VERSIONGEN_STR( s )
#define VERSIONGEN_STR( s ) #s

#ifndef BUILT_BY
#define BUILT_BY local
#endif

#ifndef BUILD_NUMBER
#define BUILD_NUMBER N/A
#endif

#define GENERATE_VERSION_INFO_STR( LIB_NAME_STR, VERSION_STR ) \
  LIB_NAME_STR " v" VERSION_STR

#define GENERATE_BUILD_INFO "[date: " __DATE__ " " __TIME__ ", built by: " VERSIONGEN_XSTR( BUILT_BY ) ", build #: " VERSIONGEN_XSTR( BUILD_NUMBER ) "]"

#define GENERATE_VERSION_INFO_EXT_STR( LIB_NAME_STR, VERSION_STR ) \
  GENERATE_VERSION_INFO_STR( LIB_NAME_STR, VERSION_STR ) " " GENERATE_BUILD_INFO

#endif /* VERSIONGEN_H_ */
