name: Build and Publish Wheels

on:
  push:
    branches:
      - main
      - github_actions
  workflow_dispatch:
    inputs:
      tag:
        description: "Git tag to build (e.g. 3.6)"
        required: true
        default: "3.6"
        type: string
      cmake_preset:
        description: "CMake preset (release, debug, relWithDebInfo)"
        required: true
        default: "release"
        type: string

jobs:
  build-wheels:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-latest ]
        python-version: [ 3.12 ]

    env:
      CIBW_BUILD_VERBOSITY: 3
      CIBW_OUTPUT_DIR: "wheelhouse"
      BUILD_TAG: "3.6.0"
      CMAKE_PRESET: "release"

    steps:
#      - name: Validate cmake_preset
#        run: |
#          allowed=("release" "debug" "relWithDebInfo")
#          preset="${{ env.CMAKE_PRESET }}"
#          if [[ ! " ${allowed[@]} " =~ " ${preset} " ]]; then
#            echo "Error: invalid cmake_preset '${preset}'. Must be one of: ${allowed[*]}"
#            exit 1
#          fi

      - name: Checkout tag
        uses: actions/checkout@v4
        with:
          ref: "github_actions"
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        shell: bash
        run: |
          if [[ "$RUNNER_OS" == "Windows" ]]; then
            choco install cmake --installargs 'ADD_CMAKE_TO_PATH=System'
            pip install --upgrade pip setuptools wheel cibuildwheel twine ninja
          else
            sudo apt-get update
            sudo apt-get install -y cmake ninja-build
            pip install --upgrade pip setuptools wheel cibuildwheel twine
          fi

      - name: Show build info
        run: |
          echo "Building tag: $env:BUILD_TAG"
          echo "Using preset: $env:CMAKE_PRESET"
          echo "Build suffix: $env:BUILD_SUFFIX"
          git rev-parse --short HEAD

      - name: Build wheels
        run: cibuildwheel --output-dir $env:CIBW_OUTPUT_DIR
